- name: Allow SSH Password Login on Localhost
  hosts: localhost
  connection: local  # This specifies that the connection is local

  tasks:
    - name: Allow password authentication in SSH config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      become: yes

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
      become: yes